# Generated by Django 4.2.4 on 2023-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_banner_remove_product_price_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='image',
            field=models.ImageField(upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='imgs/'),
        ),
    ]
